# Site settings
title: devopracy
description: 'infrastructure code for virtual democracies'
url: 'devopracy.github.io'
baseurl: '/devopracy.github.io/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Ele Munjeli'
  email: info@devopracy.net
  twitter_username: @devopracy
  facebook_username: devopracy
  github_username:  devopracy

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
